name: dart_web_application_1
description: An absolute bare-bones web app.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.6

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  intl: ^0.17.0 # For internationalization support
  shared_preferences: ^2.0.6 # To store language preference locally
  cupertino_icons: ^1.0.2 # Cupertino icons used in iOS devices

dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.0
  lints: ^2.1.0
